#!/usr/bin/env python3
"""Validate, export, install, uninstall, and audit the agent toolkit."""

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path, PurePosixPath


TOOLKIT_ROOT = Path(__file__).resolve().parent.parent
LEDGER_NAME = ".agent-toolkit-install.json"
SHARED_SKILLS_LEDGER_NAME = ".agent-toolkit-shared-skills.json"
INSTRUCTION_BLOCK_BEGIN = "# >>> agent-toolkit instructions (managed; do not edit) >>>"
INSTRUCTION_BLOCK_END = "# <<< agent-toolkit instructions (managed) <<<"
GENERATED_TEXT = "Generated by agent-toolkit"
SOURCE_DIRS = (
    ".agents/skills",
    "instructions",
    "standards",
    "templates",
    "platforms",
)
SOURCE_FILES = ("AGENTS.md", "manifest.json")
VALID_PLATFORMS = {"codex", "opencode", "github-copilot", "claude-code", "omp", "gemini"}
FORBIDDEN_SKILL_TEXT = (
    ".codex/",
    ".opencode/",
    ".github/",
    ".claude/",
    ".gemini/",
    "danger-full-access",
    "bypassPermissions",
    "SYSTEM OVERRIDE",
    "session lock",
)


class ToolkitError(Exception):
    """A user-actionable toolkit error."""


def _reject_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ToolkitError("Duplicate JSON key: {0}".format(key))
        result[key] = value
    return result


def _reject_constant(value):
    raise ToolkitError("Non-finite JSON value is not allowed: {0}".format(value))


def load_json(path):
    """Load JSON while rejecting duplicate keys and non-finite numbers."""
    try:
        return json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_reject_duplicate_keys,
            parse_constant=_reject_constant,
        )
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ToolkitError("Cannot read valid JSON from {0}: {1}".format(path, exc))


def safe_relative_path(value):
    """Return a normalized relative path or reject an unsafe value."""
    if not isinstance(value, str) or not value or "\x00" in value or "\\" in value:
        raise ToolkitError("Unsafe relative path: {0!r}".format(value))
    path = PurePosixPath(value)
    if path.is_absolute() or any(part in ("", ".", "..") for part in path.parts):
        raise ToolkitError("Unsafe relative path: {0!r}".format(value))
    if re.match(r"^[A-Za-z]:", value):
        raise ToolkitError("Unsafe relative path: {0!r}".format(value))
    return path


def ensure_within(root, relative):
    """Resolve a child path and ensure it remains under root."""
    rel = safe_relative_path(str(relative))
    root_resolved = root.resolve()
    candidate = (root / Path(*rel.parts)).resolve()
    try:
        candidate.relative_to(root_resolved)
    except ValueError:
        raise ToolkitError("Path escapes target root: {0}".format(relative))
    return candidate


def safe_operation_root(path, label):
    resolved = path.resolve()
    if resolved == Path(resolved.anchor):
        raise ToolkitError("Refusing to use the filesystem root as {0}".format(label))
    return resolved


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def file_sha256(path):
    return sha256_bytes(path.read_bytes())


def source_files(root=TOOLKIT_ROOT):
    """Return canonical source inputs in deterministic order."""
    files = []
    for relative in SOURCE_FILES:
        path = root / relative
        if path.is_file():
            files.append(path)
    for relative in SOURCE_DIRS:
        directory = root / relative
        if directory.is_dir():
            files.extend(path for path in directory.rglob("*") if path.is_file())
    return sorted(files, key=lambda item: item.relative_to(root).as_posix())


def source_digest(root=TOOLKIT_ROOT):
    digest = hashlib.sha256()
    for path in source_files(root):
        relative = path.relative_to(root).as_posix().encode("utf-8")
        digest.update(relative)
        digest.update(b"\x00")
        digest.update(path.read_bytes())
        digest.update(b"\x00")
    return digest.hexdigest()


def all_skill_names(manifest):
    names = []
    for group in ("lifecycle", "cross_cutting", "optional"):
        names.extend(manifest["skills"].get(group, []))
    return names


def bundle_skill_names(manifest, bundle):
    if bundle not in manifest.get("bundles", {}):
        raise ToolkitError("Unknown bundle: {0}".format(bundle))
    result = []
    for entry in manifest["bundles"][bundle]:
        if entry in manifest.get("skills", {}):
            result.extend(manifest["skills"][entry])
        else:
            result.append(entry)
    seen = set()
    ordered = []
    for name in result:
        if name not in seen:
            seen.add(name)
            ordered.append(name)
    return ordered


def generated_marker(version, digest, prefix="<!--", suffix="-->"):
    return "{0} {1} {2}; source-sha256: {3}; do not edit. {4}\n".format(
        prefix, GENERATED_TEXT, version, digest, suffix
    )


def parse_frontmatter(path):
    """Parse the small YAML subset used by canonical SKILL.md files."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ToolkitError("Missing YAML frontmatter in {0}".format(path))
    try:
        end = lines.index("---", 1)
    except ValueError:
        raise ToolkitError("Unclosed YAML frontmatter in {0}".format(path))
    values = {}
    current = None
    for line in lines[1:end]:
        if line.startswith((" ", "\t")):
            if current is None:
                raise ToolkitError("Invalid frontmatter indentation in {0}".format(path))
            values[current] = (values[current] + " " + line.strip()).strip()
            continue
        if ":" not in line:
            raise ToolkitError("Invalid frontmatter line in {0}: {1}".format(path, line))
        key, value = line.split(":", 1)
        key = key.strip()
        if key in values:
            raise ToolkitError("Duplicate frontmatter key in {0}: {1}".format(path, key))
        current = key
        values[key] = value.strip().lstrip(">|-").strip()
    return values


def _unique_strings(values, label, errors):
    if not isinstance(values, list) or not all(isinstance(item, str) for item in values):
        errors.append("{0} must be a list of strings".format(label))
        return []
    duplicates = sorted({item for item in values if values.count(item) > 1})
    if duplicates:
        errors.append("{0} contains duplicates: {1}".format(label, ", ".join(duplicates)))
    folded = {}
    for item in values:
        folded.setdefault(item.casefold(), []).append(item)
    collisions = [items for items in folded.values() if len(items) > 1]
    if collisions:
        errors.append("{0} contains case-insensitive collisions: {1}".format(label, collisions))
    return values


def validate_manifest(manifest, errors):
    required = {
        "schema_version",
        "name",
        "version",
        "canonical",
        "platforms",
        "skills",
        "bundles",
        "install_policy",
    }
    missing = required - set(manifest)
    if missing:
        errors.append("Manifest missing keys: {0}".format(", ".join(sorted(missing))))
        return
    if manifest["schema_version"] != 1:
        errors.append("Unsupported manifest schema_version")
    if not re.match(r"^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$", manifest["version"]):
        errors.append("Manifest version is not semantic versioning: {0}".format(manifest["version"]))
    platforms = _unique_strings(manifest["platforms"], "manifest.platforms", errors)
    unknown = set(platforms) - VALID_PLATFORMS
    if unknown:
        errors.append("Unknown platforms: {0}".format(", ".join(sorted(unknown))))
    for group in ("lifecycle", "cross_cutting", "optional"):
        _unique_strings(manifest["skills"].get(group), "manifest.skills.{0}".format(group), errors)
    _unique_strings(all_skill_names(manifest), "all manifest skills", errors)
    known_skills = set(all_skill_names(manifest))
    for bundle, entries in manifest["bundles"].items():
        _unique_strings(entries, "manifest.bundles.{0}".format(bundle), errors)
        for entry in entries:
            if entry not in manifest["skills"] and entry not in known_skills:
                errors.append("Bundle {0} references unknown skill/group: {1}".format(bundle, entry))
    for key, value in manifest["canonical"].items():
        try:
            safe_relative_path(value)
        except ToolkitError as exc:
            errors.append("manifest.canonical.{0}: {1}".format(key, exc))
    policy = manifest["install_policy"]
    if policy.get("overwrite") != "never" or policy.get("preview_required") is not True:
        errors.append("Install policy must require preview and never overwrite by default")


def validate_skills(manifest, errors, root=TOOLKIT_ROOT):
    skill_root = root / manifest["canonical"]["skills"]
    expected = set(all_skill_names(manifest))
    actual = {path.name for path in skill_root.iterdir() if path.is_dir()} if skill_root.is_dir() else set()
    if expected != actual:
        errors.append(
            "Skill directory mismatch; missing={0}, extra={1}".format(
                sorted(expected - actual), sorted(actual - expected)
            )
        )
    for name in sorted(expected & actual):
        skill_file = skill_root / name / "SKILL.md"
        if not skill_file.is_file():
            errors.append("Missing SKILL.md for {0}".format(name))
            continue
        try:
            metadata = parse_frontmatter(skill_file)
        except ToolkitError as exc:
            errors.append(str(exc))
            continue
        if set(metadata) - {"name", "description", "invocation", "role", "supersedes"}:
            errors.append("{0} frontmatter must contain only name, description, invocation, role, and supersedes".format(name))
        if metadata.get("name") != name:
            errors.append("Skill folder/name mismatch: {0}".format(name))
        description = metadata.get("description", "")
        if not description or len(description) > 1024:
            errors.append("Skill {0} needs a concise non-empty description".format(name))
        text = skill_file.read_text(encoding="utf-8")
        for token in FORBIDDEN_SKILL_TEXT:
            if token.casefold() in text.casefold():
                errors.append("Skill {0} contains non-portable text: {1}".format(name, token))
        if re.search(r"\b(?:TODO|TBD|FIXME)\b", text, re.IGNORECASE):
            errors.append("Skill {0} contains placeholder text".format(name))
        long_lines = [index for index, line in enumerate(text.splitlines(), 1) if len(line) > 120]
        if long_lines:
            errors.append("Skill {0} has lines over 120 characters: {1}".format(name, long_lines))
        metadata_file = skill_root / name / "agents" / "openai.yaml"
        if not metadata_file.is_file():
            errors.append("Skill {0} is missing agents/openai.yaml".format(name))
        for match in re.finditer(r"\[[^\]]+\]\(([^)]+)\)", text):
            reference = match.group(1).split("#", 1)[0]
            if not reference or "://" in reference or reference.startswith("#"):
                continue
            try:
                referenced = ensure_within(skill_file.parent, reference)
            except ToolkitError as exc:
                errors.append("Skill {0} has unsafe reference: {1}".format(name, exc))
                continue
            if not referenced.exists():
                errors.append("Skill {0} has broken reference: {1}".format(name, reference))



def validate_adapters(manifest, errors, root=TOOLKIT_ROOT):
    for platform in manifest["platforms"]:
        path = root / "platforms" / platform / "adapter.json"
        if not path.is_file():
            errors.append("Missing adapter descriptor for {0}".format(platform))
            continue
        adapter = load_json(path)
        if adapter.get("id") != platform:
            errors.append("Adapter ID mismatch for {0}".format(platform))
        try:
            safe_relative_path(adapter["skill_path"].replace("{name}", "skill"))
        except (KeyError, ToolkitError) as exc:
            errors.append("Unsafe or missing adapter path for {0}: {1}".format(platform, exc))
        global_block = adapter.get("global")
        if global_block is None:
            errors.append("Adapter {0} is missing a global scope block".format(platform))
        else:
            try:
                safe_relative_path(global_block["instruction_path"])
                safe_relative_path(global_block["skill_path"].replace("{name}", "skill"))
            except (KeyError, ToolkitError) as exc:
                errors.append("Unsafe or missing global path for {0}: {1}".format(platform, exc))
            command_pattern = global_block.get("command_path")
            if command_pattern:
                try:
                    safe_relative_path(command_pattern.replace("{name}", "skill"))
                except ToolkitError as exc:
                    errors.append("Unsafe global command path for {0}: {1}".format(platform, exc))


def validate_toolkit(root=TOOLKIT_ROOT):
    errors = []
    manifest = load_json(root / "manifest.json")
    validate_manifest(manifest, errors)
    if errors:
        return errors
    validate_skills(manifest, errors, root)
    validate_adapters(manifest, errors, root)
    for relative in SOURCE_DIRS:
        path = root / relative
        if path.is_symlink():
            errors.append("Canonical source directory must not be a symlink: {0}".format(path))
    for path in source_files(root):
        if path.is_symlink():
            errors.append("Canonical export input must not be a symlink: {0}".format(path))
    return errors


def yaml_value(value):
    """Render a scalar as a YAML-compatible JSON string."""
    return json.dumps(value, ensure_ascii=False)















def render_opencode_command(skill_root, name):
    """Render an OpenCode slash command that loads one skill."""
    frontmatter = parse_frontmatter(skill_root / "SKILL.md")
    description = frontmatter.get("description", "Run the {0} agent-toolkit skill".format(name))
    body = (
        "Load and run the `{0}` skill and follow its procedure for this task. "
        "Keep the skill's stop conditions and outputs as the source of truth."
    ).format(name)
    return (
        "---\ndescription: {0}\n---\n\n{1}\n".format(yaml_value(description), body)
    )


def write_text(root, relative, content):
    destination = ensure_within(root, relative)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def copy_file(source, destination_root, relative):
    if source.is_symlink():
        raise ToolkitError("Symlinked source files are not exportable: {0}".format(source))
    destination = ensure_within(destination_root, relative)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(str(source), str(destination))


def copy_tree(source, destination_root, relative_root):
    if source.is_symlink():
        raise ToolkitError("Symlinked source directories are not exportable: {0}".format(source))
    for path in sorted(source.rglob("*")):
        if path.is_symlink():
            raise ToolkitError("Symlinked source paths are not exportable: {0}".format(path))
        if path.is_file():
            relative = PurePosixPath(relative_root) / PurePosixPath(path.relative_to(source).as_posix())
            copy_file(path, destination_root, relative.as_posix())


def export_to_directory(platform, bundle, destination, root=TOOLKIT_ROOT):
    """Create one target-ready platform package in a new directory."""
    manifest = load_json(root / "manifest.json")
    if platform not in manifest["platforms"]:
        raise ToolkitError("Unsupported platform: {0}".format(platform))
    selected_skills = bundle_skill_names(manifest, bundle)
    digest = source_digest(root)
    version = manifest["version"]
    destination.mkdir(parents=True, exist_ok=False)

    copy_file(root / "AGENTS.md", destination, "AGENTS.md")
    for source_name, target_name in (
        ("instructions", ".agents/instructions"),
        ("standards", ".agents/standards"),
        ("templates", ".agents/templates"),
    ):
        copy_tree(root / source_name, destination, target_name)

    adapter = load_json(root / "platforms" / platform / "adapter.json")
    for skill_name in selected_skills:
        source = root / manifest["canonical"]["skills"] / skill_name
        target_pattern = adapter["skill_path"].replace("{name}", skill_name)
        copy_tree(source, destination, target_pattern)

    if platform == "github-copilot":
        instructions = generated_marker(version, digest) + (root / "AGENTS.md").read_text(encoding="utf-8")
        write_text(destination, adapter["instruction_path"], instructions)
    elif platform == "claude-code":
        content = generated_marker(version, digest) + "@AGENTS.md\n"
        write_text(destination, adapter["instruction_path"], content)
    elif platform == "omp":
        content = generated_marker(version, digest) + (root / "AGENTS.md").read_text(encoding="utf-8")
        write_text(destination, ".omp/AGENTS.md", content)

    metadata = {
        "schema_version": 1,
        "toolkit": manifest["name"],
        "version": version,
        "source_sha256": digest,
        "platform": platform,
        "bundle": bundle,
        "skills": selected_skills,
    }
    write_text(
        destination,
        ".agent-toolkit-package.json",
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
    )
    return metadata


def export_to_global_directory(platform, bundle, destination, root=TOOLKIT_ROOT):
    """Create one home-relative platform package for global installation.

    Skills are laid out at the shared ``.agents/skills`` location so a single
    installed copy serves every platform. Agents and instructions use the
    platform's global home-relative paths.
    """
    manifest = load_json(root / "manifest.json")
    if platform not in manifest["platforms"]:
        raise ToolkitError("Unsupported platform: {0}".format(platform))
    adapter = load_json(root / "platforms" / platform / "adapter.json")
    global_block = adapter.get("global")
    if not global_block:
        raise ToolkitError("Platform {0} has no global scope block".format(platform))

    selected_skills = bundle_skill_names(manifest, bundle)
    digest = source_digest(root)
    version = manifest["version"]
    destination.mkdir(parents=True, exist_ok=False)

    shared_skill_files = []
    for skill_name in selected_skills:
        source = root / manifest["canonical"]["skills"] / skill_name
        target_pattern = global_block["skill_path"].replace("{name}", skill_name)
        copy_tree(source, destination, target_pattern)
        for path in sorted(source.rglob("*")):
            if path.is_file():
                relative = (
                    PurePosixPath(target_pattern)
                    / PurePosixPath(path.relative_to(source).as_posix())
                )
                shared_skill_files.append(relative.as_posix())

    merge_files = []
    instruction_relative = global_block["instruction_path"]
    instruction_content = generated_marker(version, digest) + (
        root / "AGENTS.md"
    ).read_text(encoding="utf-8")
    write_text(destination, instruction_relative, instruction_content)

    command_path_pattern = global_block.get("command_path")
    if command_path_pattern:
        for skill_name in selected_skills:
            command_relative = command_path_pattern.replace("{name}", skill_name)
            command = render_opencode_command(root / manifest["canonical"]["skills"] / skill_name, skill_name)
            write_text(destination, command_relative, command)

    metadata = {
        "schema_version": 1,
        "toolkit": manifest["name"],
        "version": version,
        "source_sha256": digest,
        "platform": platform,
        "bundle": bundle,
        "scope": "global",
        "skills": selected_skills,
        "shared_skill_files": sorted(shared_skill_files),
        "merge_files": merge_files,
        "instruction_path": instruction_relative,
    }
    write_text(
        destination,
        ".agent-toolkit-package.json",
        json.dumps(metadata, indent=2, sort_keys=True) + "\n",
    )
    return metadata


def package_files(root, include_metadata=True):
    files = {}
    if not root.is_dir():
        return files
    for path in sorted(root.rglob("*")):
        if path.is_symlink():
            raise ToolkitError("Package contains a symlink: {0}".format(path))
        if path.is_file():
            relative = path.relative_to(root).as_posix()
            safe_relative_path(relative)
            if not include_metadata and relative == ".agent-toolkit-package.json":
                continue
            folded = relative.casefold()
            if any(existing.casefold() == folded and existing != relative for existing in files):
                raise ToolkitError("Case-insensitive package path collision: {0}".format(relative))
            files[relative] = file_sha256(path)
    return files


def validate_exported_package(package_root, platform, bundle, root=TOOLKIT_ROOT):
    errors = []
    if package_root.is_symlink() or not package_root.is_dir():
        return ["Package root must be a regular directory: {0}".format(package_root)]
    metadata_path = package_root / ".agent-toolkit-package.json"
    if metadata_path.is_symlink() or not metadata_path.is_file():
        return ["Package metadata must be a regular file: {0}".format(metadata_path)]
    try:
        metadata = load_json(metadata_path)
    except ToolkitError as exc:
        return [str(exc)]
    manifest = load_json(root / "manifest.json")
    if platform not in manifest["platforms"]:
        return ["Unsupported package platform: {0}".format(platform)]
    if bundle not in manifest["bundles"]:
        return ["Unsupported package bundle: {0}".format(bundle)]
    expected_metadata = {
        "toolkit": manifest["name"],
        "version": manifest["version"],
        "source_sha256": source_digest(root),
        "platform": platform,
        "bundle": bundle,
    }
    for key, expected in expected_metadata.items():
        if metadata.get(key) != expected:
            errors.append("Package metadata mismatch for {0}".format(key))
    expected_skills = set(bundle_skill_names(manifest, bundle))
    if set(metadata.get("skills", [])) != expected_skills:
        errors.append("Package skill list does not match bundle {0}".format(bundle))
    try:
        files = package_files(package_root)
    except ToolkitError as exc:
        return errors + [str(exc)]
    if "AGENTS.md" not in files:
        errors.append("Package is missing AGENTS.md")
    adapter = load_json(root / "platforms" / platform / "adapter.json")
    for skill in expected_skills:
        skill_file = adapter["skill_path"].replace("{name}", skill) + "/SKILL.md"
        if skill_file not in files:
            errors.append("Package is missing skill: {0}".format(skill))
    if platform == "github-copilot" and adapter["instruction_path"] not in files:
        errors.append("Package is missing GitHub Copilot instructions")
    if platform == "claude-code":
        instruction_path = adapter["instruction_path"]
        if instruction_path not in files or "@AGENTS.md" not in (package_root / instruction_path).read_text(encoding="utf-8"):
            errors.append("Package is missing the Claude AGENTS.md import")
    return errors


def validate_exported_global_package(package_root, platform, bundle, root=TOOLKIT_ROOT):
    errors = []
    if package_root.is_symlink() or not package_root.is_dir():
        return ["Package root must be a regular directory: {0}".format(package_root)]
    metadata_path = package_root / ".agent-toolkit-package.json"
    if metadata_path.is_symlink() or not metadata_path.is_file():
        return ["Package metadata must be a regular file: {0}".format(metadata_path)]
    try:
        metadata = load_json(metadata_path)
    except ToolkitError as exc:
        return [str(exc)]
    manifest = load_json(root / "manifest.json")
    if platform not in manifest["platforms"]:
        return ["Unsupported package platform: {0}".format(platform)]
    if bundle not in manifest["bundles"]:
        return ["Unsupported package bundle: {0}".format(bundle)]
    expected_metadata = {
        "toolkit": manifest["name"],
        "version": manifest["version"],
        "source_sha256": source_digest(root),
        "platform": platform,
        "bundle": bundle,
        "scope": "global",
    }
    for key, expected in expected_metadata.items():
        if metadata.get(key) != expected:
            errors.append("Package metadata mismatch for {0}".format(key))
    expected_skills = set(bundle_skill_names(manifest, bundle))
    if set(metadata.get("skills", [])) != expected_skills:
        errors.append("Package skill list does not match bundle {0}".format(bundle))
    try:
        files = package_files(package_root)
    except ToolkitError as exc:
        return errors + [str(exc)]
    for relative in metadata.get("shared_skill_files", []):
        if relative not in files:
            errors.append("Package is missing shared skill file: {0}".format(relative))
    adapter = load_json(root / "platforms" / platform / "adapter.json")
    global_block = adapter.get("global", {})
    instruction_relative = metadata.get("instruction_path")
    if instruction_relative:
        if instruction_relative not in files:
            errors.append("Package is missing global instruction file")
        elif GENERATED_TEXT not in (package_root / instruction_relative).read_text(encoding="utf-8"):
            errors.append("Generated marker missing from global instruction file")
    else:
        errors.append("Package metadata is missing instruction_path")
    for entry in metadata.get("merge_files", []):
        if entry.get("merge_file") not in files:
            errors.append("Package is missing merge file: {0}".format(entry.get("merge_file")))
    command_pattern = global_block.get("command_path")
    if command_pattern:
        for skill in expected_skills:
            relative = command_pattern.replace("{name}", skill)
            if relative not in files:
                errors.append("Package is missing slash command: {0}".format(skill))
    return errors


def compare_trees(expected, actual):
    expected_files = package_files(expected)
    actual_files = package_files(actual)
    missing = sorted(set(expected_files) - set(actual_files))
    extra = sorted(set(actual_files) - set(expected_files))
    changed = sorted(
        path for path in set(expected_files) & set(actual_files) if expected_files[path] != actual_files[path]
    )
    return missing, extra, changed


def package_relative_root(platform, scope):
    """Return the dist subdirectory that holds one platform package."""
    if scope == "global":
        return PurePosixPath("global") / platform
    return PurePosixPath(platform)


def atomic_export(platform, bundle, output_root, root=TOOLKIT_ROOT, scope="repository"):
    output_root = safe_operation_root(output_root, "export output")
    target = output_root / package_relative_root(platform, scope)
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink():
        raise ToolkitError("Refusing to replace symlinked export target: {0}".format(target))
    transaction = Path(tempfile.mkdtemp(prefix=".agent-toolkit-export-", dir=str(output_root)))
    staged = transaction / "new"
    previous = transaction / "previous"
    try:
        if scope == "global":
            export_to_global_directory(platform, bundle, staged, root)
            errors = validate_exported_global_package(staged, platform, bundle, root)
        else:
            export_to_directory(platform, bundle, staged, root)
            errors = validate_exported_package(staged, platform, bundle, root)
        if errors:
            raise ToolkitError("Generated package failed validation:\n- " + "\n- ".join(errors))
        if target.exists():
            target.rename(previous)
        staged.rename(target)
    except Exception:
        if not target.exists() and previous.exists():
            previous.rename(target)
        raise
    finally:
        shutil.rmtree(str(transaction), ignore_errors=True)
    return target


def check_export_drift(platform, bundle, output_root, root=TOOLKIT_ROOT, scope="repository"):
    target = output_root.resolve() / package_relative_root(platform, scope)
    if not target.is_dir():
        return ["Missing generated package: {0}".format(target)]
    with tempfile.TemporaryDirectory(prefix="agent-toolkit-check-") as temp:
        expected = Path(temp) / "package"
        if scope == "global":
            export_to_global_directory(platform, bundle, expected, root)
        else:
            export_to_directory(platform, bundle, expected, root)
        missing, extra, changed = compare_trees(expected, target)
    findings = []
    if missing:
        findings.append("Missing files: {0}".format(", ".join(missing)))
    if extra:
        findings.append("Unexpected files: {0}".format(", ".join(extra)))
    if changed:
        findings.append("Changed files: {0}".format(", ".join(changed)))
    return findings


def _destination_path(target, relative):
    path = ensure_within(target, relative)
    cursor = path
    while cursor != target.resolve():
        if cursor.is_symlink():
            raise ToolkitError("Refusing symlinked install path: {0}".format(cursor))
        cursor = cursor.parent
    return path


def ledger_name(scope="repository", platform=None):
    if scope == "global" and platform:
        return ".agent-toolkit-install-{0}.json".format(platform)
    return LEDGER_NAME


def _load_ledger(target, name=LEDGER_NAME):
    ledger_path = target / name
    if not ledger_path.exists():
        return None
    if ledger_path.is_symlink() or not ledger_path.is_file():
        raise ToolkitError("Install ledger is not a regular file: {0}".format(ledger_path))
    ledger = load_json(ledger_path)
    if ledger.get("schema_version") != 1 or not isinstance(ledger.get("files", {}), dict):
        raise ToolkitError("Unsupported or invalid install ledger")
    folded_paths = set()
    for relative, digest in ledger.get("files", {}).items():
        safe_relative_path(relative)
        folded = relative.casefold()
        if folded in folded_paths:
            raise ToolkitError("Case-insensitive path collision in install ledger: {0}".format(relative))
        folded_paths.add(folded)
        if not re.match(r"^[0-9a-f]{64}$", str(digest)):
            raise ToolkitError("Invalid ledger hash for {0}".format(relative))
    return ledger


def plan_install(package_root, target, exclude=None, ledger_file=LEDGER_NAME):
    metadata = load_json(package_root / ".agent-toolkit-package.json")
    package_hashes = package_files(package_root, include_metadata=False)
    if exclude:
        package_hashes = {
            relative: digest
            for relative, digest in package_hashes.items()
            if relative not in exclude
        }
    target = safe_operation_root(target, "install target")
    ledger = _load_ledger(target, ledger_file) if target.exists() else None
    managed = ledger.get("files", {}) if ledger else {}
    actions = []
    conflicts = []
    new_ledger_hashes = {}

    for relative, expected_hash in sorted(package_hashes.items()):
        try:
            destination = _destination_path(target, relative)
        except ToolkitError as exc:
            conflicts.append(str(exc))
            continue
        if destination.exists():
            if not destination.is_file() or destination.is_symlink():
                conflicts.append("Destination is not a regular file: {0}".format(relative))
                continue
            actual_hash = file_sha256(destination)
            if actual_hash == expected_hash:
                if relative in managed:
                    actions.append(("unchanged", relative))
                    new_ledger_hashes[relative] = expected_hash
                else:
                    actions.append(("preserve-identical-user-owned", relative))
            elif relative in managed and actual_hash == managed[relative]:
                actions.append(("update", relative))
                new_ledger_hashes[relative] = expected_hash
            elif relative in managed:
                conflicts.append("User-modified managed file: {0}".format(relative))
            else:
                conflicts.append("Existing user-owned file differs: {0}".format(relative))
        else:
            actions.append(("create", relative))
            new_ledger_hashes[relative] = expected_hash

    for relative, previous_hash in sorted(managed.items()):
        if relative in package_hashes:
            continue
        try:
            destination = _destination_path(target, relative)
        except ToolkitError as exc:
            conflicts.append(str(exc))
            continue
        if not destination.exists():
            actions.append(("already-removed", relative))
        elif destination.is_file() and not destination.is_symlink() and file_sha256(destination) == previous_hash:
            actions.append(("remove-stale", relative))
        else:
            actions.append(("preserve-modified-stale", relative))

    new_ledger = {
        "schema_version": 1,
        "toolkit": metadata.get("toolkit"),
        "version": metadata.get("version"),
        "source_sha256": metadata.get("source_sha256"),
        "platform": metadata.get("platform"),
        "bundle": metadata.get("bundle"),
        "scope": metadata.get("scope", "repository"),
        "files": new_ledger_hashes,
    }
    return actions, conflicts, new_ledger


def _prune_empty_parents(path, stop):
    cursor = path.parent
    stop = stop.resolve()
    while cursor != stop:
        try:
            cursor.rmdir()
        except OSError:
            break
        cursor = cursor.parent


def apply_install(package_root, target, exclude=None, ledger_file=LEDGER_NAME):
    actions, conflicts, new_ledger = plan_install(package_root, target, exclude, ledger_file)
    if conflicts:
        raise ToolkitError("Install conflicts:\n- " + "\n- ".join(conflicts))
    target = safe_operation_root(target, "install target")
    target.mkdir(parents=True, exist_ok=True)
    backups = {}
    created = []
    temporary_files = []
    ledger_path = target / ledger_file
    ledger_backup = ledger_path.read_bytes() if ledger_path.exists() else None
    try:
        for action, relative in actions:
            destination = _destination_path(target, relative)
            if action in ("create", "update"):
                if destination.exists():
                    backups[relative] = destination.read_bytes()
                else:
                    created.append(relative)
                destination.parent.mkdir(parents=True, exist_ok=True)
                source = package_root / relative
                temporary = destination.with_name(destination.name + ".agent-toolkit-tmp")
                temporary_files.append(temporary)
                shutil.copyfile(str(source), str(temporary))
                os.replace(str(temporary), str(destination))
            elif action == "remove-stale":
                backups[relative] = destination.read_bytes()
                destination.unlink()
                _prune_empty_parents(destination, target)
        ledger_content = json.dumps(new_ledger, indent=2, sort_keys=True) + "\n"
        write_text(target, ledger_file, ledger_content)
    except Exception as exc:
        for temporary in temporary_files:
            if temporary.exists() and temporary.is_file() and not temporary.is_symlink():
                temporary.unlink()
        for relative in created:
            destination = _destination_path(target, relative)
            if destination.exists() and destination.is_file():
                destination.unlink()
                _prune_empty_parents(destination, target)
        for relative, content in backups.items():
            destination = _destination_path(target, relative)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)
        if ledger_backup is None:
            if ledger_path.exists():
                ledger_path.unlink()
        else:
            ledger_path.write_bytes(ledger_backup)
        raise ToolkitError("Install rolled back after failure: {0}".format(exc))
    return actions


def plan_uninstall(target, ledger_file=LEDGER_NAME):
    target = safe_operation_root(target, "uninstall target")
    ledger = _load_ledger(target, ledger_file)
    if ledger is None:
        return [], []
    actions = []
    warnings = []
    for relative, installed_hash in sorted(ledger.get("files", {}).items()):
        try:
            destination = _destination_path(target, relative)
        except ToolkitError as exc:
            warnings.append(str(exc))
            continue
        if not destination.exists():
            actions.append(("already-removed", relative))
        elif destination.is_file() and not destination.is_symlink() and file_sha256(destination) == installed_hash:
            actions.append(("remove", relative))
        else:
            actions.append(("preserve-modified", relative))
            warnings.append("Preserving modified or non-regular file: {0}".format(relative))
    return actions, warnings


def apply_uninstall(target, ledger_file=LEDGER_NAME):
    target = safe_operation_root(target, "uninstall target")
    actions, warnings = plan_uninstall(target, ledger_file)
    for action, relative in actions:
        if action == "remove":
            destination = _destination_path(target, relative)
            destination.unlink()
            _prune_empty_parents(destination, target)
    ledger_path = target / ledger_file
    if ledger_path.exists() and ledger_path.is_file() and not ledger_path.is_symlink():
        ledger_path.unlink()
    return actions, warnings


def _load_shared_skills_ledger(target):
    path = target / SHARED_SKILLS_LEDGER_NAME
    if not path.exists():
        return {"schema_version": 1, "files": {}}
    if path.is_symlink() or not path.is_file():
        raise ToolkitError("Shared skills ledger is not a regular file: {0}".format(path))
    ledger = load_json(path)
    if ledger.get("schema_version") != 1 or not isinstance(ledger.get("files"), dict):
        raise ToolkitError("Unsupported or invalid shared skills ledger")
    for relative, record in ledger["files"].items():
        safe_relative_path(relative)
        if not isinstance(record, dict):
            raise ToolkitError("Invalid shared skills record for {0}".format(relative))
        if not re.match(r"^[0-9a-f]{64}$", str(record.get("hash", ""))):
            raise ToolkitError("Invalid shared skills hash for {0}".format(relative))
        if not isinstance(record.get("owners"), list):
            raise ToolkitError("Invalid shared skills owners for {0}".format(relative))
    return ledger


def plan_shared_skills(package_root, target, platform, shared_files):
    """Plan installation of ref-counted shared skill files."""
    package_hashes = package_files(package_root, include_metadata=False)
    ledger = _load_shared_skills_ledger(target)
    managed = ledger["files"]
    actions = []
    conflicts = []
    for relative in sorted(shared_files):
        expected_hash = package_hashes.get(relative)
        if expected_hash is None:
            conflicts.append("Shared skill file missing from package: {0}".format(relative))
            continue
        try:
            destination = _destination_path(target, relative)
        except ToolkitError as exc:
            conflicts.append(str(exc))
            continue
        record = managed.get(relative)
        if destination.exists():
            if not destination.is_file() or destination.is_symlink():
                conflicts.append("Shared skill destination is not a regular file: {0}".format(relative))
                continue
            actual_hash = file_sha256(destination)
            if actual_hash == expected_hash:
                if record and platform in record["owners"]:
                    actions.append(("shared-unchanged", relative))
                else:
                    actions.append(("shared-adopt", relative))
            elif record and actual_hash == record["hash"]:
                actions.append(("shared-update", relative))
            elif record:
                conflicts.append("User-modified shared skill file: {0}".format(relative))
            else:
                conflicts.append("Existing user-owned shared skill differs: {0}".format(relative))
        else:
            actions.append(("shared-create", relative))
    return actions, conflicts


def apply_shared_skills(package_root, target, platform, shared_files):
    actions, conflicts = plan_shared_skills(package_root, target, platform, shared_files)
    if conflicts:
        raise ToolkitError("Shared skill conflicts:\n- " + "\n- ".join(conflicts))
    package_hashes = package_files(package_root, include_metadata=False)
    ledger = _load_shared_skills_ledger(target)
    managed = ledger["files"]
    ledger_path = target / SHARED_SKILLS_LEDGER_NAME
    ledger_backup = ledger_path.read_bytes() if ledger_path.exists() else None
    backups = {}
    created = []
    temporary_files = []
    try:
        for action, relative in actions:
            destination = _destination_path(target, relative)
            expected_hash = package_hashes[relative]
            if action in ("shared-create", "shared-update"):
                if destination.exists():
                    backups[relative] = destination.read_bytes()
                else:
                    created.append(relative)
                destination.parent.mkdir(parents=True, exist_ok=True)
                temporary = destination.with_name(destination.name + ".agent-toolkit-tmp")
                temporary_files.append(temporary)
                shutil.copyfile(str(package_root / relative), str(temporary))
                os.replace(str(temporary), str(destination))
            record = managed.setdefault(relative, {"hash": expected_hash, "owners": []})
            record["hash"] = expected_hash
            if platform not in record["owners"]:
                record["owners"] = sorted(set(record["owners"]) | {platform})
        ledger["files"] = managed
        write_text(
            target,
            SHARED_SKILLS_LEDGER_NAME,
            json.dumps(ledger, indent=2, sort_keys=True) + "\n",
        )
    except Exception as exc:
        for temporary in temporary_files:
            if temporary.exists() and temporary.is_file() and not temporary.is_symlink():
                temporary.unlink()
        for relative in created:
            destination = _destination_path(target, relative)
            if destination.exists() and destination.is_file():
                destination.unlink()
                _prune_empty_parents(destination, target)
        for relative, content in backups.items():
            destination = _destination_path(target, relative)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)
        if ledger_backup is None:
            if ledger_path.exists():
                ledger_path.unlink()
        else:
            ledger_path.write_bytes(ledger_backup)
        raise ToolkitError("Shared skill install rolled back after failure: {0}".format(exc))
    return actions


def plan_shared_skills_uninstall(target, platform):
    """Plan removal of shared skills owned by one platform (ref-aware)."""
    ledger = _load_shared_skills_ledger(target)
    managed = ledger["files"]
    actions = []
    warnings = []
    for relative in sorted(managed):
        record = managed[relative]
        if platform not in record["owners"]:
            continue
        remaining = [owner for owner in record["owners"] if owner != platform]
        if remaining:
            actions.append(("shared-release", relative))
            continue
        try:
            destination = _destination_path(target, relative)
        except ToolkitError as exc:
            warnings.append(str(exc))
            continue
        if not destination.exists():
            actions.append(("shared-already-removed", relative))
        elif destination.is_file() and not destination.is_symlink() and file_sha256(destination) == record["hash"]:
            actions.append(("shared-remove", relative))
        else:
            actions.append(("shared-preserve-modified", relative))
            warnings.append("Preserving modified shared skill file: {0}".format(relative))
    return actions, warnings


def apply_shared_skills_uninstall(target, platform):
    actions, warnings = plan_shared_skills_uninstall(target, platform)
    ledger = _load_shared_skills_ledger(target)
    managed = ledger["files"]
    for action, relative in actions:
        record = managed.get(relative)
        if record is None:
            continue
        if action == "shared-remove":
            destination = _destination_path(target, relative)
            if destination.exists() and destination.is_file() and not destination.is_symlink():
                destination.unlink()
                _prune_empty_parents(destination, target)
        if action in ("shared-remove", "shared-already-removed", "shared-preserve-modified"):
            del managed[relative]
        elif action == "shared-release":
            record["owners"] = [owner for owner in record["owners"] if owner != platform]
    ledger_path = target / SHARED_SKILLS_LEDGER_NAME
    if managed:
        ledger["files"] = managed
        write_text(
            target,
            SHARED_SKILLS_LEDGER_NAME,
            json.dumps(ledger, indent=2, sort_keys=True) + "\n",
        )
    elif ledger_path.exists() and ledger_path.is_file() and not ledger_path.is_symlink():
        ledger_path.unlink()
    return actions, warnings







def _split_instruction_block(text):
    """Return (before, after, present) around an instruction managed block."""
    begin = text.find(INSTRUCTION_BLOCK_BEGIN)
    if begin == -1:
        return text, "", False
    end = text.find(INSTRUCTION_BLOCK_END, begin)
    if end == -1:
        raise ToolkitError("Malformed instruction block: missing end marker")
    end += len(INSTRUCTION_BLOCK_END)
    if text[end:end + 1] == "\n":
        end += 1
    return text[:begin], text[end:], True


def _wrap_instruction_block(body):
    """Wrap a generated instruction body with managed-block markers."""
    return INSTRUCTION_BLOCK_BEGIN + "\n" + body + INSTRUCTION_BLOCK_END + "\n"


def plan_instruction_block(package_root, target, instruction_relative):
    """Plan insertion of a managed instruction block into an existing file.

    The block carries the toolkit's generated instruction body. When the
    destination already exists (a user-owned file), the block is appended so
    the user's content is preserved. The file is excluded from the regular
    file ledger and tracked only through this block mechanism.
    """
    body = (package_root / instruction_relative).read_text(encoding="utf-8")
    block = _wrap_instruction_block(body)
    destination = _destination_path(target, instruction_relative)
    if destination.exists():
        if not destination.is_file() or destination.is_symlink():
            return None, ["Instruction file is not a regular file: {0}".format(instruction_relative)]
        current = destination.read_text(encoding="utf-8")
        before, after, present = _split_instruction_block(current)
        if present:
            existing_block = current[len(before):len(current) - len(after)]
            action = (
                "instruction-unchanged" if existing_block == block
                else "instruction-update"
            )
        else:
            action = "instruction-append"
    else:
        before, after, action = "", "", "instruction-create"
    return (action, instruction_relative, before, block, after), []


def apply_instruction_block(package_root, target, instruction_relative):
    planned, conflicts = plan_instruction_block(package_root, target, instruction_relative)
    if conflicts:
        raise ToolkitError("Instruction block conflicts:\n- " + "\n- ".join(conflicts))
    action, _relative, before, block, after = planned
    if action == "instruction-unchanged":
        return action
    if action == "instruction-create":
        new_content = block
    elif action == "instruction-append":
        base = before
        if base and not base.endswith("\n"):
            base += "\n"
        if base and not base.endswith("\n\n"):
            base += "\n"
        new_content = base + block
    else:
        new_content = before + block + after
    destination = _destination_path(target, instruction_relative)
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(destination.name + ".agent-toolkit-tmp")
    try:
        with temporary.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(new_content)
        os.replace(str(temporary), str(destination))
    except Exception as exc:
        if temporary.exists():
            temporary.unlink()
        raise ToolkitError("Instruction block write failed: {0}".format(exc))
    return action


def plan_instruction_unblock(target, instruction_relative):
    destination = _destination_path(target, instruction_relative)
    if not destination.exists() or destination.is_symlink() or not destination.is_file():
        return ("instruction-unblock-absent", instruction_relative)
    current = destination.read_text(encoding="utf-8")
    _before, _after, present = _split_instruction_block(current)
    return ("instruction-unblock-remove" if present else "instruction-unblock-absent", instruction_relative)


def apply_instruction_unblock(target, instruction_relative):
    action, _relative = plan_instruction_unblock(target, instruction_relative)
    if action != "instruction-unblock-remove":
        return action
    destination = _destination_path(target, instruction_relative)
    current = destination.read_text(encoding="utf-8")
    before, after, _present = _split_instruction_block(current)
    remaining = (before.rstrip("\n") + ("\n" + after.lstrip("\n") if after.strip() else "")).strip()
    if remaining:
        content = before + after
        temporary = destination.with_name(destination.name + ".agent-toolkit-tmp")
        with temporary.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(str(temporary), str(destination))
    else:
        destination.unlink()
        _prune_empty_parents(destination, target)
    return action


def global_install_parts(package_root):
    """Split a global package into regular, shared-skill, and block parts."""
    metadata = load_json(package_root / ".agent-toolkit-package.json")
    shared = set(metadata.get("shared_skill_files", []))
    merges = metadata.get("merge_files", [])
    merge_paths = {entry["merge_file"] for entry in merges}
    instruction_relative = metadata.get("instruction_path")
    exclude = shared | merge_paths
    if instruction_relative:
        exclude.add(instruction_relative)
    return metadata, shared, merges, instruction_relative, exclude


def format_actions(actions):
    return "\n".join("{0:24} {1}".format(action, path) for action, path in actions)


def selected_platforms(args, manifest):
    if getattr(args, "all", False):
        return manifest["platforms"]
    return [args.platform]


def command_validate(args):
    errors = validate_toolkit()
    if errors:
        print("Canonical toolkit validation failed:", file=sys.stderr)
        for error in errors:
            print("- {0}".format(error), file=sys.stderr)
        return 1
    print("Canonical toolkit validation passed.")
    if args.dist:
        manifest = load_json(TOOLKIT_ROOT / "manifest.json")
        for platform in manifest["platforms"]:
            for scope, validator in (
                ("repository", validate_exported_package),
                ("global", validate_exported_global_package),
            ):
                package = args.dist.resolve() / package_relative_root(platform, scope)
                package_errors = validator(package, platform, args.bundle)
                if package_errors:
                    print("Package validation failed for {0} ({1}):".format(platform, scope), file=sys.stderr)
                    for error in package_errors:
                        print("- {0}".format(error), file=sys.stderr)
                    return 1
                print("Validated generated package: {0} ({1})".format(platform, scope))
    return 0


def command_export(args):
    errors = validate_toolkit()
    if errors:
        raise ToolkitError("Canonical validation failed:\n- " + "\n- ".join(errors))
    manifest = load_json(TOOLKIT_ROOT / "manifest.json")
    for platform in selected_platforms(args, manifest):
        for scope in ("repository", "global"):
            if args.check:
                findings = check_export_drift(platform, args.bundle, args.output, scope=scope)
                if findings:
                    print("Export drift detected for {0} ({1}):".format(platform, scope), file=sys.stderr)
                    for finding in findings:
                        print("- {0}".format(finding), file=sys.stderr)
                    return 1
                print("Export is current: {0} ({1})".format(platform, scope))
            else:
                target = atomic_export(platform, args.bundle, args.output, scope=scope)
                print("Exported {0} package to {1}".format(scope, target))
    return 0


def resolve_target(args):
    """Return the operation root, defaulting global scope to the home directory."""
    if getattr(args, "target", None) is not None:
        return args.target
    if getattr(args, "scope", "global") == "global":
        return Path(os.path.expanduser("~"))
    raise ToolkitError("--target is required for repository scope")


def _prepared_package(args):
    scope = getattr(args, "scope", "global")
    if args.package:
        package = args.package.resolve()
        metadata = load_json(package / ".agent-toolkit-package.json")
        platform = metadata.get("platform")
        bundle = metadata.get("bundle")
        package_scope = metadata.get("scope", "repository")
        if args.platform and platform != args.platform:
            raise ToolkitError("Package platform does not match --platform")
        if package_scope != scope:
            raise ToolkitError(
                "Package scope {0} does not match --scope {1}".format(package_scope, scope)
            )
        if package_scope == "repository":
            errors = validate_exported_package(package, platform, bundle)
            if errors:
                raise ToolkitError("Package validation failed:\n- " + "\n- ".join(errors))
        return None, package
    if not args.platform:
        raise ToolkitError("--platform is required when --package is omitted")
    temporary = tempfile.TemporaryDirectory(prefix="agent-toolkit-install-")
    package = Path(temporary.name) / args.platform
    if scope == "global":
        export_to_global_directory(args.platform, args.bundle, package)
    else:
        export_to_directory(args.platform, args.bundle, package)
        errors = validate_exported_package(package, args.platform, args.bundle)
        if errors:
            temporary.cleanup()
            raise ToolkitError("Generated package validation failed:\n- " + "\n- ".join(errors))
    return temporary, package


def command_install(args):
    scope = getattr(args, "scope", "global")
    target = resolve_target(args)
    temporary, package = _prepared_package(args)
    try:
        if scope == "global":
            return _run_global_install(package, target, args.apply)
        actions, conflicts, _ledger = plan_install(package, target)
        print("Install plan for {0}:".format(target.resolve()))
        print(format_actions(actions) or "No file actions.")
        if conflicts:
            print("Conflicts:", file=sys.stderr)
            for conflict in conflicts:
                print("- {0}".format(conflict), file=sys.stderr)
            return 1
        if not args.apply:
            print("Dry run only. Re-run with --apply to install.")
            return 0
        applied = apply_install(package, target)
        changed = sum(action in ("create", "update", "remove-stale") for action, _ in applied)
        print("Install completed; {0} file action(s) changed the target.".format(changed))
        return 0
    finally:
        if temporary is not None:
            temporary.cleanup()


def _run_global_install(package, target, apply):
    metadata, shared, merges, instruction_relative, exclude = global_install_parts(package)
    platform = metadata.get("platform")
    ledger_file = ledger_name("global", platform)
    file_actions, conflicts, _ledger = plan_install(
        package, target, exclude=exclude, ledger_file=ledger_file
    )
    shared_actions, shared_conflicts = plan_shared_skills(package, target, platform, shared)
    instruction_preview = []
    if instruction_relative:
        planned, instruction_conflicts = plan_instruction_block(package, target, instruction_relative)
        conflicts.extend(instruction_conflicts)
        if planned is not None:
            instruction_preview.append((planned[0], planned[1]))
    conflicts.extend(shared_conflicts)

    print("Global install plan for {0} into {1}:".format(platform, target.resolve()))
    print(format_actions(file_actions + shared_actions + instruction_preview) or "No file actions.")
    if conflicts:
        print("Conflicts:", file=sys.stderr)
        for conflict in conflicts:
            print("- {0}".format(conflict), file=sys.stderr)
        return 1
    if not apply:
        print("Dry run only. Re-run with --apply to install.")
        return 0
    apply_install(package, target, exclude=exclude, ledger_file=ledger_file)
    apply_shared_skills(package, target, platform, shared)
    if instruction_relative:
        apply_instruction_block(package, target, instruction_relative)
    print("Global install completed for {0}.".format(platform))
    return 0


def command_uninstall(args):
    scope = getattr(args, "scope", "global")
    target = resolve_target(args)
    if scope == "global":
        return _run_global_uninstall(target, args.platform, args.apply)
    actions, warnings = plan_uninstall(target)
    print("Uninstall plan for {0}:".format(target.resolve()))
    print(format_actions(actions) or "No managed files found.")
    for warning in warnings:
        print("Warning: {0}".format(warning), file=sys.stderr)
    if not args.apply:
        print("Dry run only. Re-run with --apply to uninstall.")
        return 0
    applied, final_warnings = apply_uninstall(target)
    removed = sum(action == "remove" for action, _ in applied)
    print("Uninstall completed; removed {0} unchanged managed file(s).".format(removed))
    return 0 if not final_warnings else 2


def _run_global_uninstall(target, platform, apply):
    if not platform:
        raise ToolkitError("--platform is required for global uninstall")
    ledger_file = ledger_name("global", platform)
    file_actions, warnings = plan_uninstall(target, ledger_file)
    shared_actions, shared_warnings = plan_shared_skills_uninstall(target, platform)
    warnings = warnings + shared_warnings
    adapter = load_json(TOOLKIT_ROOT / "platforms" / platform / "adapter.json")
    global_block = adapter.get("global", {})
    merge_actions = []
    instruction_relative = global_block.get("instruction_path")
    instruction_action = None
    if instruction_relative:
        instruction_action = plan_instruction_unblock(target, instruction_relative)
        if instruction_action[0] != "instruction-unblock-absent":
            merge_actions.append(instruction_action)

    print("Global uninstall plan for {0} from {1}:".format(platform, target.resolve()))
    print(format_actions(file_actions + shared_actions + merge_actions) or "No managed files found.")
    for warning in warnings:
        print("Warning: {0}".format(warning), file=sys.stderr)
    if not apply:
        print("Dry run only. Re-run with --apply to uninstall.")
        return 0
    apply_uninstall(target, ledger_file)
    apply_shared_skills_uninstall(target, platform)
    if instruction_relative:
        apply_instruction_unblock(target, instruction_relative)
    print("Global uninstall completed for {0}.".format(platform))
    return 0 if not warnings else 2


def command_check_drift(args):
    manifest = load_json(TOOLKIT_ROOT / "manifest.json")
    failed = False
    for platform in selected_platforms(args, manifest):
        for scope in ("repository", "global"):
            findings = check_export_drift(platform, args.bundle, args.output, scope=scope)
            if findings:
                failed = True
                print("Drift detected for {0} ({1}):".format(platform, scope), file=sys.stderr)
                for finding in findings:
                    print("- {0}".format(finding), file=sys.stderr)
            else:
                print("No drift: {0} ({1})".format(platform, scope))
    return 1 if failed else 0


def add_platform_selector(parser):
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--platform", choices=sorted(VALID_PLATFORMS))
    group.add_argument("--all", action="store_true", help="Process every supported platform.")


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate", help="Validate canonical or generated content.")
    validate_parser.add_argument("--dist", type=Path, help="Also validate all packages under this directory.")
    validate_parser.add_argument("--bundle", default="core", choices=("core", "full", "quality"))
    validate_parser.set_defaults(handler=command_validate)

    export_parser = subparsers.add_parser("export", help="Generate platform-native packages.")
    add_platform_selector(export_parser)
    export_parser.add_argument("--bundle", default="core", choices=("core", "full", "quality"))
    export_parser.add_argument("--output", type=Path, default=TOOLKIT_ROOT / "dist")
    export_parser.add_argument("--check", action="store_true", help="Check output without changing it.")
    export_parser.set_defaults(handler=command_export)

    install_parser = subparsers.add_parser("install", help="Preview or install a platform package.")
    install_parser.add_argument("--platform", choices=sorted(VALID_PLATFORMS))
    install_parser.add_argument("--package", type=Path, help="Use an existing generated package.")
    install_parser.add_argument("--bundle", default="core", choices=("core", "full", "quality"))
    install_parser.add_argument("--scope", default="global", choices=("repository", "global"))
    install_parser.add_argument(
        "--target",
        type=Path,
        default=None,
        help="Install root. Required for repository scope; defaults to the home directory for global scope.",
    )
    install_parser.add_argument("--apply", action="store_true", help="Apply the previewed safe changes.")
    install_parser.set_defaults(handler=command_install)

    uninstall_parser = subparsers.add_parser("uninstall", help="Preview or remove unchanged managed files.")
    uninstall_parser.add_argument("--platform", choices=sorted(VALID_PLATFORMS))
    uninstall_parser.add_argument("--scope", default="global", choices=("repository", "global"))
    uninstall_parser.add_argument(
        "--target",
        type=Path,
        default=None,
        help="Uninstall root. Optional; defaults to the home directory for global scope, required for repository scope.",
    )
    uninstall_parser.add_argument("--apply", action="store_true", help="Apply the previewed safe removals.")
    uninstall_parser.set_defaults(handler=command_uninstall)

    drift_parser = subparsers.add_parser("check-drift", help="Compare generated output with canonical sources.")
    add_platform_selector(drift_parser)
    drift_parser.add_argument("--bundle", default="core", choices=("core", "full", "quality"))
    drift_parser.add_argument("--output", type=Path, default=TOOLKIT_ROOT / "dist")
    drift_parser.set_defaults(handler=command_check_drift)
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.handler(args)
    except ToolkitError as exc:
        print("Error: {0}".format(exc), file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("Interrupted.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
